src/java/controllers/EhdokasController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controllers;

import controllers.util.JsfUtil;
import entity.Ehdokas;
import entity.User;
import facades.EhdokasFacade;
import java.io.Serializable;
import java.util.List;
import java.util.Map;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;

/**
 * Kontrolleri, joka tarjoaa CRUD-operaatiot ja listauksen ehdokas-olioille.
 * @author Ismo
 */
@ManagedBean
@ViewScoped
public class EhdokasController implements Serializable {

    @EJB
    private EhdokasFacade facade;

    private List<Ehdokas> ehdokkaat;
    private Ehdokas selectedEhdokas;

    private final static String EDIT_HEADER = "Muokkaa ehdokkaan tietoja";
    private final static String NEW_HEADER = "Luo uusi ehdokas";

    /**
     * Initialisaatiometodi. Hakee kaikki ehdokkaat listaan ja asettaa oletuksena valituksi ehdokkaaksi kirjautuneen ehdokkaan.
     * 
     */
    @PostConstruct
    public void init() {
        ehdokkaat = facade.findAll();
        Map map = FacesContext.getCurrentInstance().getExternalContext().getSessionMap();
        User user = (User) map.get("User");
        if (user != null) {
            selectedEhdokas = user.getEhdokas();
        }
    }

    /**
     * Palauttaa listan ehdokkaista
     * @return Lista ehdokkaista
     */
    public List<Ehdokas> getEhdokkaat() {
        return ehdokkaat;
    }

    /**
     * Asettaa ehdokkaat
     * @param ehdokkaat 
     */
    public void setEhdokkaat(List<Ehdokas> ehdokkaat) {
        this.ehdokkaat = ehdokkaat;
    }

    /**
     * Palauttaa kontrollerissa valitun ehdokkaan
     * @return Valittu ehdokas
     */
    public Ehdokas getSelectedEhdokas() {
        return selectedEhdokas;
    }

    /**
     * Asettaa valitun ehdokkaan
     * @param selectedEhdokas Ehdokas, joka halutaan valita
     */
    public void setSelectedEhdokas(Ehdokas selectedEhdokas) {
        this.selectedEhdokas = selectedEhdokas;
    }

    /**
     * Päivittää olemassa olevan ehdokkaan tiedot tai luo uuden ehdokkaan, 
     * mikäli ehdokas ei ole vielä tietokannassa.
     */
    public void updateSelected() {
        if (selectedEhdokas != null) {
            if (selectedEhdokas.getEhdokasId() != null) {
                facade.edit(selectedEhdokas);
                JsfUtil.addSuccessMessage("Ehdokas päivitettiin onnistuneesti");
            } else {
                facade.create(selectedEhdokas);
                ehdokkaat.add(selectedEhdokas);
                JsfUtil.addSuccessMessage("Uusi ehdokas tallenneettiin onnistuneesti");
            }
        }
    }

    /**
     * Poistaa valitun ehdokkaan tietokannasta ja kontrollerista.
     */
    public void removeSelected() {
        ehdokkaat.remove(selectedEhdokas);
        facade.remove(selectedEhdokas);
        JsfUtil.addSuccessMessage("Ehdokas poistettiin onnistuneesti");
    }

    /**
     * Asettaa uuden (tyhjän) ehdokkaan valituksi ehdokkaaksi
     */
    public void createNew() {
        selectedEhdokas = new Ehdokas();
    }

    /**
     * Palauttaa otsikon riippuen onko kontrollerissa valittuna uusi ehdokas
     * vai jo olemassa oleva. 
     * @return "Muokkaa ehdokkaan tietoja", jos ehdokas on olemassa, tai 
     * "Luo uusi ehdokas", jos ehdokasta ei vielä ole tietokannassa.
     */
    public String getHeaderString() {
        if (selectedEhdokas != null) {
            if (selectedEhdokas.getEhdokasId() != null) {
                return EDIT_HEADER;
            } else {
                return NEW_HEADER;
            }
        }
        return "";
    }
}

web/admin/ehdokkaat/Kaikki.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">
    <ui:composition template="/template.xhtml">
        <ui:define name="title">Admin paneeli</ui:define>
        <ui:define name="body">
            <h:form id='ehdokkaat-form'>
                <!-- Breadcrumb-tyyliset linkit-->
                <p:breadCrumb style="background:white; text-shadow:none; margin-bottom:1em;">
                    <p:menuitem value="Etusivu" url="/"/>
                    <p:menuitem value="Admin" url="/admin"/>
                    <p:menuitem value="Ehdokkaat" url="/admin/ehdokkaat/Kaikki.xhtml"/>
                </p:breadCrumb>
                
                <!-- Datataulu, johon haetaan kaikkien ehdokkaiden tiedot kontrollerista -->
                <p:dataTable editable="true" 
                             value="#{ehdokasController.ehdokkaat}" 
                             var="item" 
                             style="background:white">
                    <!-- Otsikkorivi -->
                    <f:facet name="header">
                        <h:outputText value="Ehdokkaat"/>
                    </f:facet>
                    
                    <p:column headerText="Id" width="20">
                        <h:outputText value="#{item.ehdokasId}"/>
                    </p:column>
                    <p:column headerText="Etunimi" width="60">
                        <h:outputText value="#{item.etunimi}"/>
                    </p:column>
                    <p:column headerText="Sukunimi" width="100">
                        <h:outputText value="#{item.sukunimi}"/>
                    </p:column>
                    <p:column headerText="Puolue">
                        <h:outputText value="#{item.puolue}"/>
                    </p:column>
                    <p:column headerText="Ikä" width="20">
                        <h:outputText value="#{item.ika}"/>
                    </p:column>
                    <p:column headerText="Ammatti">
                        <h:outputText value="#{item.ammatti}"/>
                    </p:column>
                    <!-- Muokkaus ja poistamisnapit -->
                    <p:column style='text-align:center; width:140px;'>
                        <p:commandButton style='margin:5px;color:black;margin-right:15px'
                                         icon="fa fa-edit"
                                         title="Muokkaa"             
                                         oncomplete="PF('edit-dialog').show()"
                                         update=":ehdokas-form main-messages edit-dialog">
                            <f:setPropertyActionListener target='#{ehdokasController.selectedEhdokas}'
                                                         value="#{item}"/>
                        </p:commandButton>
                        <p:commandButton style='margin:5px'
                                         title='Poista'
                                         icon="fa fa-trash" 
                                         action="#{ehdokasController.removeSelected()}"
                                         update="main-messages ehdokkaat-form">
                            <f:setPropertyActionListener target='#{ehdokasController.selectedEhdokas}'
                                                         value="#{item}"/>
                        </p:commandButton>
                    </p:column>
                    
                    <!-- Taulun alatunniste, jossa nappi uuden ehdokkaan lisäämiselle -->
                    <f:facet name="footer">
                        <p:commandButton value="Lisää ehdokas" 
                                         action="#{ehdokasController.createNew()}"
                                         update="ehdokas-form edit-dialog"
                                         oncomplete='PF("edit-dialog").show()'
                                         style="right:0px;">
                        </p:commandButton>
                    </f:facet>
                </p:dataTable>

            </h:form>
            <!-- Ehdokkaan tietojen muokkaus dialogi -->
            <p:dialog modal='true' id='edit-dialog' width="50%" position="center" 
                      widgetVar="edit-dialog" 
                      header="#{ehdokasController.headerString}" 
                      styleClass="dialog">
                <p:ajax event="close" update=":ehdokkaat-form" />
                <!-- Dialogin sisältö tuodaan erillisestä ehdokasform.xhtml tiedostosta -->
                <ui:include src="/ehdokasform.xhtml" id="ehdokas-form"></ui:include>
            </p:dialog>

        </ui:define>

    </ui:composition>
</html>