src/java/controllers/EhdokasController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controllers;

import controllers.util.JsfUtil;
import entity.Ehdokas;
import entity.User;
import facades.EhdokasFacade;
import java.io.Serializable;
import java.util.List;
import java.util.Map;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;

/**
 * Kontrolleri, joka tarjoaa CRUD-operaatiot ja listauksen ehdokas-olioille.
 * @author Ismo
 */
@ManagedBean
@ViewScoped
public class EhdokasController implements Serializable {

    @EJB
    private EhdokasFacade facade;

    private List<Ehdokas> ehdokkaat;
    private Ehdokas selectedEhdokas;

    private final static String EDIT_HEADER = "Muokkaa ehdokkaan tietoja";
    private final static String NEW_HEADER = "Luo uusi ehdokas";

    /**
     * Initialisaatiometodi. Hakee kaikki ehdokkaat listaan ja asettaa oletuksena valituksi ehdokkaaksi kirjautuneen ehdokkaan.
     * 
     */
    @PostConstruct
    public void init() {
        ehdokkaat = facade.findAll();
        Map map = FacesContext.getCurrentInstance().getExternalContext().getSessionMap();
        User user = (User) map.get("User");
        if (user != null) {
            selectedEhdokas = user.getEhdokas();
        }
    }

    /**
     * Palauttaa listan ehdokkaista
     * @return Lista ehdokkaista
     */
    public List<Ehdokas> getEhdokkaat() {
        return ehdokkaat;
    }

    /**
     * Asettaa ehdokkaat
     * @param ehdokkaat 
     */
    public void setEhdokkaat(List<Ehdokas> ehdokkaat) {
        this.ehdokkaat = ehdokkaat;
    }

    /**
     * Palauttaa kontrollerissa valitun ehdokkaan
     * @return Valittu ehdokas
     */
    public Ehdokas getSelectedEhdokas() {
        return selectedEhdokas;
    }

    /**
     * Asettaa valitun ehdokkaan
     * @param selectedEhdokas Ehdokas, joka halutaan valita
     */
    public void setSelectedEhdokas(Ehdokas selectedEhdokas) {
        this.selectedEhdokas = selectedEhdokas;
    }

    /**
     * Päivittää olemassa olevan ehdokkaan tiedot tai luo uuden ehdokkaan, 
     * mikäli ehdokas ei ole vielä tietokannassa.
     */
    public void updateSelected() {
        if (selectedEhdokas != null) {
            if (selectedEhdokas.getEhdokasId() != null) {
                facade.edit(selectedEhdokas);
                JsfUtil.addSuccessMessage("Ehdokas päivitettiin onnistuneesti");
            } else {
                facade.create(selectedEhdokas);
                ehdokkaat.add(selectedEhdokas);
                JsfUtil.addSuccessMessage("Uusi ehdokas tallenneettiin onnistuneesti");
            }
        }
    }

    /**
     * Poistaa valitun ehdokkaan tietokannasta ja kontrollerista.
     */
    public void removeSelected() {
        ehdokkaat.remove(selectedEhdokas);
        facade.remove(selectedEhdokas);
        JsfUtil.addSuccessMessage("Ehdokas poistettiin onnistuneesti");
    }

    /**
     * Asettaa uuden (tyhjän) ehdokkaan valituksi ehdokkaaksi
     */
    public void createNew() {
        selectedEhdokas = new Ehdokas();
    }

    /**
     * Palauttaa otsikon riippuen onko kontrollerissa valittuna uusi ehdokas
     * vai jo olemassa oleva. 
     * @return "Muokkaa ehdokkaan tietoja", jos ehdokas on olemassa, tai 
     * "Luo uusi ehdokas", jos ehdokasta ei vielä ole tietokannassa.
     */
    public String getHeaderString() {
        if (selectedEhdokas != null) {
            if (selectedEhdokas.getEhdokasId() != null) {
                return EDIT_HEADER;
            } else {
                return NEW_HEADER;
            }
        }
        return "";
    }
}

src/java/controllers/LoginController.java
package controllers;

import entity.User;
import facades.UserFacade;
import java.io.Serializable;
import java.security.Principal;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;

/**
 * Yksinkertainen controlleri, jonka avulla palveluun voidaan kirjautua sisään
 * ja ulos.
 *
 * @author Ismo
 */
@ManagedBean
@SessionScoped
public class LoginController implements Serializable {

    private static final long serialVersionUID = 3254181235309041386L;

    private static Logger log = Logger.getLogger(LoginController.class.getName());

    @EJB
    private UserFacade userEJB;

    private String email;
    private String password;
    private User user;

    /**
     * Yrittää kirjata käyttäjän sisään palveluun LoginControllerin sen
     * hetkisellä sähköpostiosoitteella ja salasanalla.
     *
     * @return Sivun nimi, jolle navigoidaan kirjautumisen tuloksena.
     */
    public String login() {
        FacesContext context = FacesContext.getCurrentInstance();
        ExternalContext externalContext = context.getExternalContext();
        HttpServletRequest request = (HttpServletRequest) externalContext.getRequest();

        // Yritetään kirjautua sisään
        try {
            request.login(email, password);
            // Jos kirjautuminen onnistui, tallennetaan käyttäjä sessioon
            Principal principal = request.getUserPrincipal();
            this.user = userEJB.find(principal.getName());
            Map<String, Object> sessionMap = externalContext.getSessionMap();
            sessionMap.put("User", user);

            // Laitetaan login-succesful viesti FacesMessage-palveluun käyttäen setKeepMessagesia, 
            // jotta ilmoitus näkyy myös uudella sivulla.
            externalContext.getFlash().setKeepMessages(true);
            context.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "Kirjauduttiin sisään onnistuneesti!", null));

        } catch (ServletException e) {
            context.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Kirjautuminen epäonnistui", "Tarkista sähköpostiosoite ja salasana"));
            return "index";
        }
        // Jos käyttäjä on ehdokas, ohjataan suoraan vastaa-sivulle
        if (request.isUserInRole("ehdokas")) {
            return "/vastaa?faces-redirect=true";
            // Jos käyttäjä on admin, ohjataan suoraan admin sivulle
        } else if (request.isUserInRole("admin")) {
            return "/admin/index.xhtml?faces-redirect=true";
            // Jos käyttäjä on toimittaja, ohjataan kysymykset sivulle
        } else if (request.isUserInRole("toimittaja")) {
            return "/Kysymykset?faces-redirect=true";
        }
        return "/index?faces-redirect=true";
    }

    /**
     * Kirjaa kirjautuneen käyttäjän ulos palvelusta.
     *
     * @return Sivun nimi, jolle navigoidaan uloskirjautumisen jälkeen.
     */
    public String logout() {
        FacesContext context = FacesContext.getCurrentInstance();
        HttpServletRequest request = (HttpServletRequest) context.getExternalContext().getRequest();
        context.getExternalContext().getFlash().setKeepMessages(true);

        // Yritetään kirjautua ulos ja näytetään tulos FacesMessagella
        try {
            this.user = null;
            request.logout();
            // Tyhjennetään sessio
            ((HttpSession) context.getExternalContext().getSession(false)).invalidate();
            
            context.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "Kirjauduttiin ulos onnistuneesti!", null));
        } catch (ServletException e) {
            log.log(Level.SEVERE, "Uloskirjautuminen epäonnistui!", e);
            context.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_FATAL, "Uloskirjautuminen epäonnistui!", "Mikäli ongelma toistuu, ota yhteyttä ylläpitoon."));
        }
        // Navigoidaan käyttäjä takaisin etusivulle
        return "/index?faces-redirect=true";
    }

    /**
     * Palauttaa sisään kirjatun käyttäjän.
     *
     * @return Sisään kirjautunut käyttäjä.
     */
    public User getAuthenticatedUser() {
        return user;
    }

    /**
     * Palauttaa kirjautumiseen käytettävän sähköpostiosoitteen arvon.
     *
     * @return Sähköpostiosoite.
     */
    public String getEmail() {
        return email;
    }

    /**
     * Asettaa kirjautumiseen käytettävän e-mail tunnuksen.
     *
     * @param email Kirjautumiseen käytettävä sähköpostiosoite.
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Palauttaa kirjautumiseen käytettävän salasanan.
     *
     * @return salasana
     */
    public String getPassword() {
        return password;
    }

    /**
     * Asettaa kirjautumiseen käytettävän salasanan.
     *
     * @param password Salasana.
     */
    public void setPassword(String password) {
        this.password = password;
    }
}

src/java/controllers/VastaaController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controllers;

import entity.Ehdokas;
import entity.Kysymys;
import entity.User;
import entity.Vastaus;
import java.io.IOException;
import java.io.Serializable;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import org.primefaces.context.RequestContext;

/**
 *
 * @author Ismo
 */
@SessionScoped
@ManagedBean(name = "vastaaController")
public class VastaaController implements Serializable {

    private Logger logger = Logger.getLogger(getClass().getName());
    private Ehdokas ehdokas;

    private List<Kysymys> kysymykset;
    private Vastaus[] vastaukset;
    
    private int vastattuCount;
    private int currentIndex;

    /**
     * Vastauksen numeroarvoja vastaavat tekstit. 
     */
    private final String[] kuvaukset = new String[]{
        "",
        "Täysin eri mieltä",
        "Jokseenkin eri mieltä",
        "En osaa sanoa",
        "Jokseenkin samaa mieltä",
        "Täysin samaa mieltä"};

    @EJB
    private facades.KysymysFacade kysymysFacade;

    @EJB
    private facades.VastausFacade vastausFacade;

    /**
     * Valmistelee kontrollerin alustamalla kysymykset, vastaukset ja 
     * ehdokkaan tiedot
     */
    @PostConstruct
    private void prepareModel() {

        // Haetaan käyttäjä sessiosta
        FacesContext c = FacesContext.getCurrentInstance();
        Map map = c.getExternalContext().getSessionMap();
        User user = (User) map.get("User");
        ehdokas = user.getEhdokas();

        // Haetaan kysymykset ja alustetaan saman kokoinen taulu vastauksille
        kysymykset = kysymysFacade.findAll();
        vastaukset = new Vastaus[kysymykset.size()];

        currentIndex = 0;

        // Haetaan jo olemassa olevat vastaukset tilapäiseen listaan.
        List<Vastaus> tempVastaukset = vastausFacade.findByEhdokas(ehdokas.getEhdokasId());

        // Käydään kysymykset läpi ja asetetaan samalle indeksille vastaustauluun 
        // tietokannasta luettu vastaus tai uusi vastaus-olio, 
        // joka samalla myös tallennetaan tietokantaan.
        for (int i = 0; i < kysymykset.size(); i++) {
            int kysymysId = kysymykset.get(i).getKysymysId();
            for (Vastaus v : tempVastaukset) {
                if (v.getVastausPK().getKysymysId() == kysymysId) {
                    vastaukset[i] = v;
                }
            }
            if (vastaukset[i] == null) {
                vastaukset[i] = new Vastaus(ehdokas.getEhdokasId(), kysymysId);
                vastausFacade.create(vastaukset[i]);
            }
        }
    }

    /**
     * Palauttaa arvon onko kyseisellä indeksillä olevaan kysymykseen vastattu
     *
     * @param index Haettu indeksi
     * @return True, jos indeksin kysymykseen on vastattu
     */
    public boolean isAnswered(int index) {
        return (vastaukset[index].getVastaus() != null);
    }

    /**
     * Tallentaa vastauksen
     *
     * @return Sivu, jolla navigoidaan tallennuksen tuloksena.
     */
    public String save() {
        vastausFacade.edit(getCurrentVastaus());
        return "vastaa";
    }

    /**
     * Siirtyy seuraavaan kysymykseen ja samalla päivittää vastauksen
     * tietokantaan
     *
     * @return Sivu, jolle navigoidaan toiminnon tuloksena
     */
    public String next() {
        vastausFacade.edit(getCurrentVastaus());
        currentIndex++;
        return "vastaa";
    }

    /**
     * Siirtyy edelliseen kysymykseen ja samalla päivittää vastauksen
     * tietokantaan
     *
     * @return Sivu, jolle navigoidaan toiminnon tuloksena
     */
    public String previous() {
        vastausFacade.edit(getCurrentVastaus());
        currentIndex--;
        return "vastaa";
    }

    /**
     * Siirtyy indeksin mukaiseen kysymykseen ja samalla päivittää vastauksen
     * tietokantaan
     *
     * @return Sivu, jolle navigoidaan toiminnon tuloksena
     */
    public String setIndex(int index) {
        vastausFacade.edit(getCurrentVastaus());
        currentIndex = index;
        return "vastaa";
    }

    /**
     * Palauttaa tämänhetkistä indeksia vastaavan kysymyksen.
     *
     * @return Tämän hetkinen kysymys
     */
    public Kysymys getCurrent() {
        return kysymykset.get(currentIndex);
    }

    /**
     * Palauttaa tämänhetkistä indeksia vastaavan vastauksen
     *
     * @return Tämän hetkinen vastaus
     */
    public Vastaus getCurrentVastaus() {
        return vastaukset[currentIndex];
    }

    /**
     * Palauttaa vastausvaihtoehtojen (1-5) kuvaukset.
     * 
     * @return Taulukko, jossa kuvaukset eri vastausvaihtoehdoille.
     */
    public String[] getKuvaukset() {
        return kuvaukset;
    }

    /**
     * Palauttaa taulukossa vastaukset kaikkiin kysymyksiin
     * 
     * @return Taulukko vastauksia
     */
    public Vastaus[] getVastaukset() {
        return vastaukset;
    }

    
    /**
     * Palauttaa aktiivisen ehdokkaan
     * 
     * @return Ehdokas
     */
    public Ehdokas getEhdokas() {
        return ehdokas;
    }

    /**
     * Palauttaa kysymykselle otsikon muodossa "Kysymys 1/19"
     * 
     * @return Otsikko stringinä
     */
    public String getTitle() {
        return "Kysymys " + (currentIndex + 1) + " / " + getCount();
    }

    /**
     * Palauttaa kysymysten määrän
     * @return kysymysten määrä
     * 
     */
    public int getCount() {
        return kysymykset.size();
    }

    /**
     * Palauttaa aktiivisen indeksin
     * @return Aktiivinen indeksi
     */
    public int getCurrentIndex() {
        return currentIndex;
    }

    /**
     * Palauttaa kysymykset listana
     * @return Lista kysymyksiä
     */
    public List<Kysymys> getKysymykset() {
        return kysymykset;
    }
    
    public void finish() {
        for (int i = 0; i < getCount(); i++) {
            if (!isAnswered(i)) {
                RequestContext.getCurrentInstance().execute("PF('warn-dialog').show()");
                return;
            }
        }
        try {
            FacesContext.getCurrentInstance().getExternalContext().redirect("lopetus.xhtml");
        } catch (IOException ex) {
            Logger.getLogger(VastaaController.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}

web/index.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<!-- Vaalikoneen etusivu -->
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">
    <ui:composition template="/template.xhtml">
        <ui:define name="title">Etusivu</ui:define>
        <ui:define name="body">
            <h:body>
                <!-- Tervetuloteksti, joka näytetään ennen käyttäjän kirjautmista -->
                <p:panel rendered="#{empty loginController.authenticatedUser}">
                    <h3>Tervetuloa lanttumaan vaalikoneeseen. Ole hyvä ja kirjaudu sisään aloittaaksesi</h3>
                </p:panel>
                <!-- Admin-roolin linkit -->
                <p:panel rendered="#{request.isUserInRole('admin')}"
                         header="Käyttäjäryhmän linkit (Admin)">
                    <p:link href="/admin/" value="Admin panel" />
                </p:panel>
                <!-- Ehdokas-roolin linkit -->
                <p:panel rendered="#{request.isUserInRole('ehdokas')}"
                         header="Käyttäjäryhmän linkit (Ehdokas)">
                    <p:link href="/vastaa.xhtml" value="Vastaamaan" />
                </p:panel>
                <!-- Toimittaja-roolin linkit -->
                <p:panel rendered="#{request.isUserInRole('toimittaja')}"
                         header="Käyttäjäryhmän linkit (Toimittaja)">
                    <p:link href="/Kysymykset.xhtml" value="Kysymykset" /> <br/>
                    <p:link href="/ListaaKysymykset" value="Kysymykset (JSP)"/>
                </p:panel>
                <p:panel header="REST API">
                    <p:link href="/webapi/ehdokkaat" value="Ehdokkaat" /> <br/>
                    <p:link href="/webapi/kysymykset" value="Kysymykset" /> <br/>
                    <p:link href="/webapi/vastaukset" value="Vastaukset" />
                </p:panel>

            </h:body>
        </ui:define>
    </ui:composition>
</html>

web/lopetus.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            Yhteenveto
        </ui:define>
        <ui:define name="body">
            <!-- Paneeli, jossa kiitosteksti -->
            <p:panel style="margin:1em;background:var(--main-white)">
                <h3>
                    <h:outputText value="Kiitoksia vastauksistanne #{loginController.authenticatedUser.ehdokas.etunimi}!
                                  Voitte vielä tarkistaa antamanne vastaukset alapuolelta ja halutessanne muuttaa niitä palaamalla kyselyyn."/>
                </h3>
                <p:link outcome="vastaa" value="Takaisin kyselyyn"/>
            </p:panel>
            <!-- Luodaan paneelit kaikista kysymyksistä ja niiden vastauksista (For-looppi) -->
            <p:repeat step="1"
                      offset="0"
                      size="#{vastaaController.count}" 
                      value="#{vastaaController.kysymykset}" 
                      var="kysymys" 
                      varStatus="varStatus">
                <p:panel header="#{varStatus.index+1} - #{kysymys.kysymys}"
                         style=" width:80%; margin: 1em auto; background:var(--main-white)">

                    <h:outputText style="font-weight:bold"
                                  value='#{vastaaController.kuvaukset[vastaaController.vastaukset[varStatus.index].vastaus]}'/> <br/><br/>
                    <h:outputText value="#{vastaaController.vastaukset[varStatus.index].kommentti}"/>
                </p:panel>
            </p:repeat>
        </ui:define>
    </ui:composition>

</html>

web/vastaa.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <!-- Otetaan käyttöön template.xhtml -->    
    <ui:composition template="/template.xhtml">
        <!-- Määritetään sivun alaotsikko, jota käytetään templatessa -->
        <ui:define name="title">
            Vastaaminen
        </ui:define>
        
        <!-- Määritetään templaten pääosioon asetettavat asiat -->
        <ui:define name="body">
            
            <!-- Ehdokkaan tiedot näyttävä paneeli, jonka sisältämä 
            lomake tuodaan ehdokasform.xhtml tiedostosta -->
            <p:panel header='Ehdokkaan tiedot' 
                     id="ehdokas-panel"
                     styleClass = 'gap'
                     closable='true'
                     toggleable='true'>

                <ui:include src="/ehdokasform.xhtml">
                </ui:include>
            </p:panel>

            <!-- Vastauslomake -->
            <h:form id="answer-form">
                <!-- Oikean reunan navigaatiopaneeli, johon luodaan dynaamisesti
                napit jokaista kysymystä varten. Nappien tyyli määräytyy niiden 
                vastaus statuksen mukaan eli vastatut näyttävät eriltä, 
                kuin ei vastatut -->
                <p:panel id="question-nav" header="Navigaatio" style='margin-top:1em; float:right; width:25%'>
                    <p:repeat offset="0" 
                              size="#{vastaaController.count}" 
                              step="1" 
                              value="#{vastaaController.kysymykset}" 
                              var="kysymys" 
                              varStatus="repeatStatus">
                        <!-- Ei vastatut kysymykset -->
                        <p:commandButton styleClass='question-btn not-answered'
                                         action="#{vastaaController.setIndex(repeatStatus.index)}" 
                                         value="#{repeatStatus.index+1}"
                                         rendered="#{not vastaaController.isAnswered(repeatStatus.index) 
                                                     and vastaaController.currentIndex != repeatStatus.index}"
                                         update='answer-form'>
                        </p:commandButton>
                        <!-- Vastatut kysymykset -->
                        <p:commandButton styleClass="question-btn answered"
                                         action="#{vastaaController.setIndex(repeatStatus.index)}" 
                                         value="#{repeatStatus.index+1}"
                                         rendered="#{vastaaController.isAnswered(repeatStatus.index) 
                                                     and vastaaController.currentIndex != repeatStatus.index}"
                                         update='answer-form'>
                        </p:commandButton>
                        <!-- Aktiivinen kysymys -->
                        <p:commandButton styleClass="question-btn current"
                                         action="#{vastaaController.setIndex(repeatStatus.index)}" 
                                         value="#{repeatStatus.index+1}"
                                         rendered="#{vastaaController.currentIndex == repeatStatus.index}"
                                         update='answer-form'>
                        </p:commandButton>
                    </p:repeat>
                </p:panel>

                <!-- Vasemman puolen paneeli, jossa vastausvaihtoehdot ja kommenttikenttä -->
                <div id="left-panel">
                    <!-- Kysymyksen tiedot näyttävä paneeli -->
                    <p:panel id="question-panel" 
                             header="#{vastaaController.title}" 
                             styleClass='gap'
                             style="height:95px">
                        <!--<h:outputText value="Kysymys #{vastaaController.currentIndex+1} / #{vastaaController.count} "/>-->
                        <h:outputText value="#{vastaaController.current.kysymys}" />
                    </p:panel>
                    <!-- Vastaus paneeli, josta käyttäjä valitsee vastauksensa -->
                    <p:panel header='Vastaus'
                             id="answer-panel" 
                             styleClass='gap'
                             >
                        <p:selectOneRadio id="vastausNro" layout="pageDirection" value="#{vastaaController.currentVastaus.vastaus}">
                            <f:selectItem itemLabel="Täysin eri mieltä" itemValue="1"/>
                            <f:selectItem itemLabel="Jokseenkin eri mieltä" itemValue="2"/>
                            <f:selectItem itemLabel="Ei mielipidettä" itemValue="3"/>
                            <f:selectItem itemLabel="Jokseenkin samaa mieltä" itemValue="4"/>
                            <f:selectItem itemLabel="Täysin samaa mieltä" itemValue="5"/> 
                        </p:selectOneRadio>
                    </p:panel>
                    <p:panel header='Kommentti' 
                             id="kommenttiText"
                             styleClass='gap'>
                        <p:inputTextarea value='#{vastaaController.currentVastaus.kommentti}'
                                         counterTemplate="{0} kirjainta jäljellä" 
                                         rows='4'
                                         style='width:100%'
                                         autoResize="true" 
                                         maxlength="50" 
                                         label='Perustelu' 
                                         placeholder="Kirjoita perustelu"
                                         counter='display'>
                        </p:inputTextarea><br></br>
                    </p:panel>
                    <h:outputText id="display" style="margin-top: 0.3em;float: right;font-size:0.8em" />
                </div>
                
                <!-- Edellinen/Seuraava/Lopetus -painikkeet -->
                <div style='width:70%;border:none;clear:both;height:60px'>
                    <p:commandButton value="Edellinen" 
                                     action="#{vastaaController.previous()}" 
                                     rendered='#{vastaaController.currentIndex gt 0}'
                                     update='answer-form'
                                     />
                    <p:commandButton action="#{vastaaController.next()}"
                                     style='float:right'
                                     value="Seuraava" 
                                     rendered='#{vastaaController.currentIndex lt (vastaaController.count-1)}'
                                     update='answer-form'/>
                    <p:commandButton action="#{vastaaController.finish()}" 
                                     value="Lopeta" 
                                     style='float:right' 
                                     rendered='#{vastaaController.currentIndex eq (vastaaController.count-1)}'
                                     />

                </div>
                
                <!-- Dialogi, joka näytetään, jos käyttäjä yrittää lopettaa kyselyn vastaamatta kaikkiin kysymyksiin -->
                <p:dialog id="warn-dialog"
                          widgetVar = 'warn-dialog'
                          header="Haluatko jatkaa?"
                          modal="true">
                    <p:panel style="margin:1em">
                        <h:outputText value="Et ole vielä vastannut kaikkiin kysymyksiin. Haluatko jatkaa yhteenvetoon?"/>
                        <f:facet name="footer">
                            <p:commandButton value="Takaisin" oncomplete="PF('warn-dialog').hide()"/>
                            <p:commandButton value="Jatka" action="lopetus"/>
                        </f:facet>
                    </p:panel>
                </p:dialog>
            </h:form>
        </ui:define>
    </ui:composition>

</html>